### ISSUE TITLE
request shape should remove adjacent slashes from the path

### ISSUE THREAD

**Issue by maplebed** [honeycombio/urlshaper#1]
The normalized request shape should do things like eliminate adjacent slashes. For example, /v1//api is the same as /v1/api, and the two // should collapse to one / in the shape. Additionally, patterns should match on the normalized version, so you don't need two patterns for /v1//api and /v1/api.

**Comment by vreynolds** [comment]
Hello,

As we enter 2022 Q1, we are trimming our OSS backlog. We will be closing this issue as it is a low priority for us to fix. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
